spring:
  datasource:
   url: jdbc:h2:mem:hulkdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   username: nn
   password: nn
   driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create      
    database-platform: org.hibernate.dialect.H2Dialect   
    properties:
      hibernate:
        show_sql: true
        format_sql: false 
  h2:
    console.enabled: true  
junit: 
  jupiter:
    testmethod:
      order:
        default: org.junit.jupiter.api.MethodOrderer$DisplayName